#!/usr/bin/env python3
"""Bulk-generate Hermes skills from a TSV list."""
from pathlib import Path

ROOT = Path("/root/VirgoYT-Hermes/skills")
TEMPLATE = """---
name: {name}
description: "{description}"
version: 0.1.0
author: darkvirgoyt-beep, Hermes Agent
license: MIT
platforms: [linux, macos, windows]
metadata:
  hermes:
    tags: [{tags}]
    related_skills: []
---

# {title}

Use when {trigger}.

## Procedure

1. {step1}
2. {step2}
3. {step3}

## Verification

- {verify1}
- {verify2}
- {verify3}
"""
rows = [
("python-debugging","software-development","Debug Python runtime, traceback, and package issues.","python,debugging","Capture the exact traceback.","Inspect venv, imports, and env.","Check dependencies and type errors.","Reproduce with a minimal script.","Verify fix without breaking tests.","Check dependency compatibility."),
("javascript-debugging","software-development","Debug browser/Node.js runtime and async issues.","javascript,debugging","Capture console/network errors.","Inspect async flow and scope.","Check bundler/runtime mismatch.","Verify in target runtime.","No regression in callers.","Check bundler/runtime config."),
("typescript-debugging","software-development","Debug TS types, generics, and build errors.","typescript,debugging","Read compiler errors exactly.","Trace generic/type inference.","Check tsconfig and lib settings.","Run typecheck and build.","No type regression.","Check type-level compatibility."),
("rust-debugging","software-development","Debug Rust compile errors, lifetimes, and panics.","rust,debugging","Read compiler message and code.","Trace ownership and borrowing.","Check trait bounds and cfg.","Run cargo check/test.","No unsafe regression.","Check edition and MSRV."),
("go-debugging","software-development","Debug Go race, build, and goroutine issues.","go,debugging","Read panic/log output.","Trace goroutine and channels.","Check module versions.","Run go test -race.","No deadlock regression.","Check Go version/modules."),
("java-debugging","software-development","Debug JVM errors, classpath, and memory issues.","java,debugging","Read stacktrace and cause.","Inspect classpath and versions.","Check GC/memory settings.","Run targeted unit tests.","No classloader regression.","Check JDK compatibility."),
("cpp-debugging","software-development","Debug C++ ABI, UB, and build/link errors.","cpp,debugging","Capture compiler/linker errors.","Inspect headers and ABI.","Check stdlib/toolchain versions.","Run minimal reproducer.","No ABI regression.","Check compiler flags."),
("react-debugging","software-development","Debug React render, state, and hook issues.","react,debugging","Capture component error boundary.","Inspect state/props/hooks.","Check suspense and memo.","Verify in dev/prod modes.","No render regression.","Check concurrent features."),
("vue-debugging","software-development","Debug Vue reactivity, router, and component issues.","vue,debugging","Capture runtime/console errors.","Inspect reactivity and setup.","Check plugin/router config.","Verify component behavior.","No reactivity regression.","Check Vue version compatibility."),
("django-debugging","software-development","Debug Django ORM, middleware, and request issues.","django,debugging","Read traceback and middleware chain.","Inspect settings and URLs.","Check DB/migrations/cache.","Run manage.py test.","No auth/middleware regression.","Check version compatibility."),
("flask-debugging","software-development","Debug Flask app context, blueprints, and extensions.","flask,debugging","Read traceback and request context.","Inspect app factory and config.","Check extension setup and order.","Run pytest/flask test client.","No blueprint regression.","Check extension compatibility."),
("fastapi-debugging","software-development","Debug FastAPI routes, validation, and dependency issues.","fastapi,debugging","Read OpenAPI/validation errors.","Inspect routers and schemas.","Check middleware and auth.","Run pytest/testclient.","No schema regression.","Check Pydantic v2 compatibility."),
("spring-debugging","software-development","Debug Spring Boot starters, autoconfig, and actuator.","spring,debugging","Read startup logs and error report.","Inspect bean wiring and profiles.","Check property sources.","Run spring test slices.","No bean wiring regression.","Check Spring Boot version."),
("docker-debugging","software-development","Debug Docker build, runtime, and network issues.","docker,debugging","Capture build/run logs.","Inspect Dockerfile layers.","Check network/mounts/env.","Rebuild with cache disabled.","No image regression.","Check engine version."),
("kubernetes-debugging","software-development","Debug K8s pods, services, and RBAC issues.","kubernetes,debugging","Read pod events and logs.","Inspect manifests and labels.","Check RBAC and networking.","Run kubectl describe/diff.","No cluster-wide regression.","Check K8s version/docs."),
("terraform-debugging","software-development","Debug Terraform plan/apply and provider errors.","terraform,debugging","Read plan/apply error output.","Inspect state and providers.","Check versions and backend.","Run terraform plan.","No state drift regression.","Check provider versions."),
("ansible-debugging","software-development","Debug Ansible playbooks, vars, and connectivity.","ansible,debugging","Read task failure and vars.","Inspect inventory and facts.","Check connection plugins.","Run ansible-playbook --check.","No idempotency regression.","Check Ansible version."),
("sql-debugging","software-development","Debug SQL queries, indexes, and transactions.","sql,debugging","Capture query error and plan.","Inspect schema and indexes.","Check isolation and locks.","Run EXPLAIN and test cases.","No data regression.","Check DB version compatibility."),
("mongodb-debugging","software-development","Debug MongoDB queries, indexes, and schema issues.","mongodb,debugging","Capture query/profile output.","Inspect indexes and schema.","Check drivers and version.","Run explain and tests.","No query regression.","Check server version."),
("redis-debugging","software-development","Debug Redis latency, memory, and eviction issues.","redis,debugging","Read slowlog and memory stats.","Inspect keyspace and config.","Check clients and persistence.","Run redis-cli tests.","No data loss regression.","Check Redis version."),
("elasticsearch-debugging","software-development","Debug Elasticsearch mapping, query, and cluster issues.","elasticsearch,debugging","Read shard/allocation logs.","Inspect mappings and analyzers.","Check cluster health and settings.","Run cat APIs and queries.","No mapping regression.","Check ES version compatibility."),
("spark-debugging","software-development","Debug Spark jobs, shuffle, and memory issues.","spark,debugging","Read executor/stage logs.","Inspect DAG and partitioning.","Check memory and serialization.","Run job with debug UI.","No data skew regression.","Check Spark version."),
("pytorch-debugging","research","Debug PyTorch CUDA, autograd, and training issues.","pytorch,debugging","Read runtime/cuda error.","Inspect model and data pipeline.","Check device/dtype/versions.","Run minimal forward/backward.","No training regression.","Check CUDA/torch versions."),
("tensorflow-debugging","research","Debug TF graphs, sessions, and device placement.","tensorflow,debugging","Read runtime/device error.","Inspect graph and ops.","Check version compatibility.","Run minimal graph/session.","No graph regression.","Check TF runtime version."),
("huggingface-debugging","research","Debug HF models, tokenizers, and pipelines.","huggingface,debugging","Read model/tokenizer error.","Inspect config and revisions.","Check cache and versions.","Run pipeline offline.","No model regression.","Check HF library version."),
("langchain-debugging","research","Debug LangChain chains, tools, and memory.","langchain,debugging","Read chain/tool error.","Inspect prompts and parsers.","Check provider config and retries.","Run chain with mock tools.","No chain regression.","Check langchain version."),
("security-audit","security","Audit code, auth, secrets, and dependency risk.","security,audit,owasp","Inventory sensitive paths.","Scan auth/secrets/dependencies.","Map trust boundaries and inputs.","Check findings against exploits.","No secret exposure.","Verify fixes with scans."),
("secrets-management","security","Scan, rotate, and store secrets safely.","security,secrets,vault","Identify secret stores.","Scan repos for leaked keys.","Check rotation and access logs.","Verify least-privilege access.","No leaked credentials.","Audit access and rotation."),
("oauth-security","security","Audit OAuth flows, PKCE, tokens, and redirects.","security,oauth,auth","Map auth endpoints and flows.","Inspect tokens and scopes.","Check redirect/CORS/CSRF.","Run auth flow tests.","No token leakage.","Verify state/nonce usage."),
("penetration-testing","security","Plan and report safe penetration tests.","security,pentest,red-team","Define scope and rules of engagement.","Enumerate targets and trust zones.","Run authorized tests only.","Report findings with evidence.","No unauthorized access.","Verify remediation steps."),
("cryptography-usage","security","Audit encryption, hashing, and key management.","security,crypto,auth","Locate crypto usage points.","Inspect algorithms and key sizes.","Check KMS/HSM integration.","Verify randomness and padding.","No weak crypto usage.","Check algorithm selection."),
("linux-system-administration","devops","Manage Linux users, disks, logs, and services.","linux,sysadmin,devops","Capture system state and logs.","Inspect services and mounts.","Check permissions and SELinux/AppArmor.","Verify with dry-run or test host.","No service outage.","Check distro release notes."),
("bash-scripting","software-development","Write and debug portable Bash automation.","bash,shell,scripting","Read script and error output.","Inspect quoting, exit codes, and paths.","Check POSIX portability.","Run shellcheck and tests.","No silent failure regression.","Check shell version compatibility."),
("git-workflow","software-development","Use Git safely for branches, merges, and recovery.","git,version-control","Read repo status and history.","Inspect branches and remotes.","Check hooks and permissions.","Verify status and tests.","No history rewrite on shared branch.","Check git version."),
("networking-basics","software-development","Diagnose host/network connectivity and DNS issues.","networking,dns,connectivity","Capture ping/traceroute/dig output.","Inspect interfaces and routes.","Check firewall and DNS config.","Verify end-to-end connectivity.","No firewall regression.","Check network namespace."),
("api-design","software-development","Design REST/GraphQL APIs with clear contracts.","api,design,backend","List resources and operations.","Draft schema/contract and errors.","Review auth, rate limits, and versioning.","Validate with consumers/tests.","Contract remains backward compatible.","Review API docs."),
("graphql-design","software-development","Design GraphQL schemas, resolvers, and authorization.","graphql,api,design","Define domain types and queries.","Draft schema and resolvers.","Check N+1 and auth boundaries.","Validate with schema checks/tests.","No resolver regression.","Check federation boundaries."),
("microservices-design","software-development","Design service boundaries, contracts, and failure modes.","microservices,architecture","Identify bounded contexts.","Define APIs, queues, and data ownership.","Review deployment and observability.","Validate with contract tests.","No tight coupling introduced.","Check SLOs and ownership."),
("event-driven-design","software-development","Design events, schemas, consumers, and replay safety.","events,architecture,messaging","Define event contracts and owners.","Design topics and ordering.","Check idempotency and DLQs.","Validate with schema tests.","No schema-breaking change.","Check consumer compatibility."),
("database-modeling","software-development","Model relational schemas, migrations, and indexes.","database,schema,modeling","Gather entities and relationships.","Draft schema and migrations.","Review indexes and constraints.","Validate with migration tests.","No data loss on migration.","Check rollback procedure."),
("redis-caching","software-development","Design cache keys, TTLs, and invalidation rules.","redis,cache,performance","Identify hot reads and latency.","Define key schema and TTLs.","Check invalidation and stampede protection.","Validate hit/miss behavior.","No stale data regression.","Check eviction policy."),
("queue-design","software-development","Design message queues, retries, and DLQ handling.","queue,messaging,reliability","Define producer/consumer contracts.","Choose broker and topology.","Check retries, ordering, and backpressure.","Validate with load tests.","No message loss regression.","Check dead-letter handling."),
("observability-design","software-development","Design metrics, logs, traces, and alerting rules.","observability,monitoring,sre","Identify critical user journeys.","Define SLIs/SLOs and signals.","Check cardinality and sampling.","Validate dashboards and alerts.","No alert fatigue.","Check retention and cost."),
("ci-cd-design","devops","Design pipelines, promotion, and rollback flows.","ci-cd,devops,automation","Map build/test/deploy stages.","Draft pipeline and secrets handling.","Check caching and artifacts.","Validate pipeline locally.","No broken main after merge.","Check promotion gates."),
("gitops-design","devops","Design GitOps with declarative infra and drift detection.","gitops,devops,infrastructure","Define repo structure and environments.","Draft sync and approval rules.","Check secrets and drift detection.","Validate with dry-run apply.","No manual drift accepted.","Check RBAC and audit."),
("capacity-planning","devops","Plan compute, storage, and concurrency headroom.","capacity,performance,sre","Measure current load and peaks.","Project growth and seasonality.","Check bottlenecks and tail latency.","Validate with load tests.","No SLO breach under peak.","Check cost model."),
("incident-response","devops","Run blameless incident response and postmortems.","incident,sre,oncall","Detect and declare incident.","Triage and mitigate quickly.","Preserve evidence and timeline.","Validate recovery and monitoring.","No unresolved action items.","Review timeline accuracy."),
("disaster-recovery","devops","Design backups, restore drills, and RTO/RPO.","disaster-recovery,backup","Identify critical datasets.","Draft backup cadence and storage.","Check encryption and retention.","Validate restore procedure.","No data corruption on restore.","Check RTO/RPO targets."),
("cost-optimization","cloud","Optimize cloud spend without breaking reliability.","cloud,cost,finops","Collect current spend and usage.","Identify idle and oversized resources.","Check reserved/savings plans.","Validate savings without SLO drop.","No hidden reliability cost.","Check budget alerts."),
("multi-cloud-design","cloud","Design workloads across cloud providers safely.","cloud,multi-cloud,architecture","Identify provider-specific dependencies.","Draft abstraction and failover.","Check networking, identity, and data sync.","Validate cross-cloud failover.","No hard provider lock-in.","Check egress and latency."),
("serverless-design","cloud","Design serverless functions, events, and cold-start handling.","serverless,cloud,events","Define event sources and contracts.","Draft function boundaries and timeouts.","Check cold-start and retries.","Validate with load and errors.","No hidden warm-instance dependency.","Check provider limits."),
("edge-computing","cloud","Design edge deployments, sync, and offline behavior.","edge,cloud,offline","Identify latency-sensitive logic.","Draft edge/runtime split.","Check sync, auth, and fallback.","Validate offline and failover.","No stale-state surprise.","Check bandwidth constraints."),
("low-latency-design","cloud","Design low-latency systems with caching and batching.","latency,performance,architecture","Measure p50/p99 targets.","Reduce critical path and sync.","Check caching, batching, and pooling.","Validate under production load.","No latency hotspot remains.","Check tail behavior."),
("data-pipeline-design","data-engineering","Design batch/stream pipelines with schema contracts.","data,pipeline,streaming","Define sources, sinks, and ownership.","Draft job topology and schemas.","Check backpressure and replay.","Validate with sample datasets.","No schema drift accepted.","Check SLA and ownership."),
("data-modeling","data-engineering","Model dimensional/normalized datasets for analytics.","data,modeling,analytics","Define business metrics and grain.","Draft dimensions and facts.","Check keys and slowly changing dimensions.","Validate with query tests.","No metric drift.","Check lineage and ownership."),
("etl-design","data-engineering","Design extract/transform/load jobs and quality gates.","etl,data,engineering","Map sources and targets.","Draft transformations and schedules.","Check nullability and deduplication.","Validate with data quality tests.","No duplicate or partial load.","Check idempotency."),
("stream-processing","data-engineering","Design stream processing with windowing and ordering.","streaming,kafka,flink","Define event keys and windows.","Draft processors and state stores.","Check ordering and late data.","Validate with replay tests.","No state corruption.","Check retention and recovery."),
("data-warehousing","data-engineering","Design warehouse schemas, partitions, and marts.","warehouse,sql,analytics","Define business questions and marts.","Draft star/snowflake schemas.","Check partitions and clustering.","Validate with report tests.","No metric drift.","Check refresh cadence."),
("feature-engineering","machine-learning","Transform raw data into model-ready features.","ml,features,data","Define prediction objective.","Draft features and leakage checks.","Check normalization and encoding.","Validate with offline metrics.","No target leakage.","Check feature registry."),
("model-training","machine-learning","Train, validate, and checkpoint ML models safely.","ml,training,experiments","Define loss and success metric.","Split data and configure training.","Check overfitting and seed.","Validate with held-out test.","No data leakage.","Check reproducibility."),
("model-evaluation","machine-learning","Evaluate model quality, calibration, and bias.","ml,evaluation,metrics","Choose primary and safety metrics.","Run stratified evaluation slices.","Check calibration and errors.","Report failures and fixes.","No hidden subgroup failure.","Check benchmark protocol."),
("model-serving","machine-learning","Serve models with latency, scaling, and rollback.","ml,serving,inference","Define latency and throughput SLA.","Package model and pre/postprocessing.","Check batching and autoscaling.","Validate with load tests.","No traffic-impacting rollout.","Check shadow/canary."),
("mlops-design","machine-learning","Design ML pipelines, registries, and monitoring.","mlops,ml,platform","Define training and serving contracts.","Draft registry and pipelines.","Check drift and retraining triggers.","Validate with experiments.","No silent model drift.","Check governance and lineage."),
("prompt-engineering","machine-learning","Design prompts for reliability, format, and safety.","prompting,llm,ml","Define task and output schema.","Draft prompt and constraints.","Add verification and examples.","Validate across model versions.","No unsafe drift.","Check token and latency budget."),
("fine-tuning","machine-learning","Fine-tune models safely with data and eval gates.","fine-tuning,ml,training","Prepare dataset and splits.","Configure LoRA/full fine-tune.","Check overfitting and safety.","Validate on held-out set.","No capability regression.","Check dataset license."),
("embedding-design","machine-learning","Design text/embedding pipelines and retrieval.","embeddings,retrieval,rag","Define query and corpus domains.","Choose model and chunking.","Check indexing and freshness.","Validate with recall tests.","No stale index regression.","Check dimensionality and cost."),
("computer-vision","machine-learning","Build and debug image/video pipelines and models.","computer-vision,ml","Define input contracts and augmentations.","Draft model and preprocessing.","Check calibration and latency.","Validate with visual tests.","No safety blind spots.","Check privacy/compliance."),
("speech-processing","machine-learning","Build and debug ASR/TTS audio pipelines and models.","speech,audio,ml","Define audio contracts and formats.","Draft preprocessing and model.","Check noise robustness and latency.","Validate with speaker tests.","No privacy leak in transcripts.","Check format compatibility."),
("recommendation-systems","machine-learning","Design retrieval, ranking, and diversity for recommendations.","recommendations,ml,ranking","Define objective and constraints.","Draft candidate and rank stages.","Check diversity and fairness.","Validate with offline and online tests.","No popularity bias regression.","Check legal/compliance."),
("time-series-forecasting","machine-learning","Forecast time series with seasonality and drift handling.","time-series,forecasting,ml","Define horizon and frequency.","Draft features and model.","Check seasonality and holidays.","Validate with backtesting.","No target leakage.","Check drift monitoring."),
("reinforcement-learning","machine-learning","Train RL agents with stable reward and safety wrappers.","reinforcement-learning,ml","Define environment and reward.","Draft policy and training loop.","Check exploration and safety.","Validate with evaluation episodes.","No unsafe policy release.","Check simulator fidelity."),
("federated-learning","machine-learning","Train across devices with privacy and aggregation.","federated-learning,privacy","Define client selection and rounds.","Draft aggregation and updates.","Check privacy and stragglers.","Validate convergence tests.","No raw data leakage.","Check compliance."),
("natural-language-processing","machine-learning","Build NLP pipelines for text classification and extraction.","nlp,ml,text","Define labels and schema.","Draft tokenization and model.","Check OOV and domain shift.","Validate with error analysis.","No toxic-output regression.","Check language coverage."),
("transformer-architecture","machine-learning","Implement and debug transformer models and attention.","transformer,architecture,deep-learning","Define model shape and attention.","Draft layers and masking.","Check memory and numerical stability.","Validate with small synthetic batch.","No NaN/Inf regression.","Check implementation against paper."),
("diffusion-models","machine-learning","Train and sample diffusion image/audio models.","diffusion,generative,ml","Define noise schedule and loss.","Draft UNet and sampler.","Check mode collapse and artifacts.","Validate with sample quality metrics.","No harmful-content regression.","Check compute and memory."),
("generative-ai-safety","machine-learning","Test generative models for safety, jailbreaks, and leakage.","generative-ai,safety,red-teaming","Define prohibited content categories.","Draft test prompts and graders.","Check refusals and fallback behavior.","Validate with red-team tests.","No unblocked harmful output.","Check policy alignment."),
("data-privacy","security","Implement data minimization, masking, and consent.","privacy,data,compliance","Map sensitive data fields.","Draft masking and retention rules.","Check access and audit.","Validate with privacy tests.","No PII exposure.","Check regulation requirements."),
("vulnerability-management","security","Triage CVEs, patch priority, and remediation.","security,cve,patching","Inventory software and exposures.","Triage severity and exploitability.","Check patch and workaround.","Validate fix and regression tests.","No exposed critical CVE.","Check patch compatibility."),
("supply-chain-security","security","Audit dependencies, SBOM, and build integrity.","security,supply-chain,devops","Map dependencies and builders.","Scan SBOM and signatures.","Check provenance and pinning.","Verify reproducibility.","No untrusted dependency accepted.","Check CI provenance."),
("identity-and-access-management","security","Design RBAC, ABAC, SSO, and least privilege.","iam,auth,security","Map roles and resources.","Draft policies and mappings.","Check privilege escalation paths.","Validate access reviews.","No overprivileged access.","Check audit logs."),
("network-security","security","Harden networks with segmentation and TLS.","network,security,tls","Map trust zones and traffic.","Draft segmentation and rules.","Check TLS and certificate hygiene.","Validate with scans/tests.","No plaintext sensitive traffic.","Check certificate expiry."),
("cloud-security","security","Secure cloud IAM, storage, and logging.","cloud,security,identity","Inventory cloud resources.","Review IAM and storage policies.","Check logging and encryption.","Validate with posture checks.","No public sensitive storage.","Check cloud provider controls."),
("application-security","security","Harden apps with input validation and secure defaults.","appsec,security,input-validation","Map trust boundaries.","Review input handling and auth.","Check defaults and error handling.","Validate with security tests.","No injection or auth bypass.","Check OWASP Top 10."),
("devsecops","devops","Integrate security scanning into CI/CD safely.","devsecops,security,ci-cd","Identify pipeline injection points.","Add scans and gates.","Check secrets and permissions.","Validate pipeline and rollback.","No false-positive blocking.","Check scan tooling."),
("observability-engineering","devops","Build metrics, logs, traces, and dashboards.","observability,monitoring,sre","Instrument critical paths.","Define SLOs and alerts.","Check cardinality and sampling.","Validate dashboards and paging.","No paging fatigue.","Check retention and cost."),
("incident-management","devops","Coordinate incidents with clear roles and comms.","incident,oncall,sre","Declare incident and assign roles.","Triage and mitigate.","Record timeline and comms.","Validate recovery and learning.","No unresolved action items.","Review timeline accuracy."),
("platform-engineering","devops","Build internal developer platforms and golden paths.","platform,devx,infrastructure","Survey developer pain points.","Draft templates and pipelines.","Check access and guardrails.","Validate adoption and SLOs.","No hidden coupling.","Check DX feedback."),
("site-reliability-engineering","devops","Run services with SLOs, error budgets, and toil reduction.","sre,reliability,oncall","Define SLOs and error budgets.","Triage toil and risks.","Check runbooks and automation.","Validate by reducing toil.","No SLO burn without action.","Check oncall rotation."),
("chaos-engineering","devops","Test resilience with controlled failure injection.","chaos,reliability,testing","Identify critical failure modes.","Design safe experiments.","Check blast radius and rollback.","Validate recovery behavior.","No customer impact.","Check experiment hygiene."),
("disaster-recovery-testing","devops","Test restores, failover, and backup integrity.","disaster-recovery,backup,testing","Define RTO/RPO scenarios.","Run controlled failover tests.","Check backup and restore integrity.","Validate recovery procedure.","No data loss or split brain.","Check runbook accuracy."),
("compliance-engineering","security","Map systems to compliance controls and evidence.","compliance,audit,security","Identify applicable frameworks.","Map controls to system behavior.","Collect evidence and logs.","Validate with auditors or tests.","No control gaps.","Check policy version."),
("privacy-engineering","security","Implement privacy by design and data-subject workflows.","privacy,compliance,data","Map personal data flows.","Design minimization and retention.","Check consent and rights workflows.","Validate with DPIAs.","No unlawful processing.","Check regulation requirements."),
("cryptography-engineering","security","Implement auth, signing, and key rotation safely.","crypto,auth,security","Identify secrets and key usage.","Choose algorithms and libraries.","Check rotation and KMS.","Validate with integration tests.","No weak key or cipher chosen.","Check algorithm agility."),
("red-teaming","security","Simulate adversary tactics safely and report findings.","red-team,security,adversary","Define scope and rules.","Model threat actors and goals.","Run controlled attacks only.","Report findings with evidence.","No unauthorized access.","Verify remediation steps."),
("blue-teaming","security","Detect, contain, and remediate security incidents.","blue-team,detection,response","Monitor detection sources.","Investigate alerts and artifacts.","Contain and remediate.","Validate recovery and hardening.","No persistent access remains.","Check detection coverage."),
("threat-modeling","security","Model threats, mitigations, and trust boundaries.","threat-modeling,security","Map assets and actors.","Identify STRIDE threats.","Rank risk and mitigations.","Validate mitigations in design.","No unmitigated critical threats.","Check boundary assumptions."),
("api-security","security","Harden APIs with auth, rate limits, and validation.","api,security,auth","Map endpoints and trust zones.","Review auth, input, and rate limiting.","Check secrets and logging.","Validate with security tests.","No auth bypass or injection.","Check OWASP API Top 10."),
("mobile-security","security","Harden mobile apps with storage, transport, and runtime checks.","mobile,security,android","Map sensitive data and flows.","Review storage, transport, and runtime.","Check obfuscation and rooting behavior.","Validate with pen tests.","No plaintext secrets.","Check platform controls."),
("iot-security","security","Secure devices, firmware, and telemetry.","iot,security,firmware","Map device trust and update path.","Review boot, transport, and auth.","Check telemetry and privacy.","Validate with firmware tests.","No unauthenticated admin path.","Check supply chain."),
("secure-coding","software-development","Write code with safe defaults and validation.","secure-coding,review,security","Review input boundaries and trust.","Apply validation and error handling.","Check auth, crypto, and logging.","Validate with security tests.","No injection or auth flaw.","Check language-specific pitfalls."),
("code-review","software-development","Review code for correctness, security, and maintainability.","code-review,quality,security","Read diff and risk areas.","Check logic, tests, and APIs.","Review security and performance.","Summarize findings by severity.","No unresolved high-risk issue.","Check regression tests."),
("testing-strategy","software-development","Design unit/integration/E2E test coverage.","testing,quality,automation","Map critical paths and risks.","Choose test levels and tools.","Check flake and data hygiene.","Run targeted coverage report.","No critical path uncovered.","Check test reliability."),
("test-automation","software-development","Automate reliable UI/API tests with CI.","automation,testing,ci","Identify stable test surfaces.","Draft tests and fixtures.","Check flake tolerance and isolation.","Run in CI pipeline.","No flaky master branch.","Check environment parity."),
("performance-engineering","software-development","Profile and optimize latency, memory, and throughput.","performance,profiling,optimization","Profile hot paths and memory.","Reduce allocations and sync.","Check caching and concurrency.","Benchmark before/after.","No hidden latency regression.","Check profiling methodology."),
("memory-profiling","software-development","Profile heap, leaks, and allocation hotspots.","memory,profiling,debugging","Capture heap and timeline.","Identify retained objects.","Check listener/handle leaks.","Run heap diff before/after.","No leak regression.","Check platform-specific behavior."),
("database-performance","software-development","Optimize queries, indexes, and connection pools.","database,performance,sql","Capture slow query and waits.","Inspect indexes and plans.","Check pool and transaction scope.","Run benchmark with production-like data.","No regression on critical queries.","Check plan stability."),
("api-performance","software-development","Optimize HTTP latency, payload, and caching.","api,performance,http","Capture latency and payload sizes.","Inspect headers and caching.","Check batching and compression.","Run load test with realistic clients.","No latency regression.","Check cache invalidation."),
("frontend-performance","software-development","Optimize web app bundle, render, and runtime.","frontend,performance,web","Capture load and runtime metrics.","Inspect bundle and waterfalls.","Check lazy loading and caching.","Run Lighthouse or RUM.","No Lighthouse regression.","Check Core Web Vitals."),
("accessibility-engineering","ui-ux-pro-max","Build inclusive UI with keyboard, screen reader, and contrast.","accessibility,a11y,ui","Audit keyboard and semantics.","Fix contrast and focus order.","Check screen reader announcements.","Run a11y tooling and manual checks.","No a11y regression.","Check WCAG level target."),
("internationalization","ui-ux-pro-max","Implement i18n with locale-safe formatting and layout.","i18n,locale,ui","Audit hardcoded strings.","Draft locale data and formatting.","Check pluralization and RTL.","Validate with multiple locales.","No broken layout in long strings.","Check locale coverage."),
("design-system-architecture","ui-ux-pro-max","Design tokens, components, and composition rules.","design-system,ui,tokens","Define tokens and component contracts.","Draft composition and variants.","Check a11y and theming.","Validate with Storybook/tests.","No visual regression.","Check token consistency."),
("responsive-design","ui-ux-pro-max","Design adaptive layouts across breakpoints and inputs.","responsive,layout,ui","Define breakpoints and constraints.","Draft adaptive layout rules.","Check touch and desktop flows.","Validate across viewports.","No overflow or tap-target regression.","Check content priority."),
("design-review","ui-ux-pro-max","Review UI designs for clarity, hierarchy, and accessibility.","design-review,ui,critique","Review screens and flows.","Check hierarchy, contrast, and copy.","Validate against accessibility rules.","Summarize issues by severity.","No critical usability blockers.","Check platform conventions."),
("information-architecture","ui-ux-pro-max","Organize content, navigation, and search structure.","ia,ux,navigation","Map user goals and content inventory.","Draft hierarchy and navigation.","Check search and labeling.","Validate with tree testing.","No orphaned content.","Check findability."),
("user-research","ui-ux-pro-max","Plan and synthesize user interviews and usability tests.","user-research,ux,interviews","Define research questions and recruitment.","Run interviews/tests.","Synthesize findings and priorities.","Report insights with evidence.","No unsupported design assumptions.","Check sample and bias."),
("usability-testing","ui-ux-pro-max","Run moderated and unmoderated usability tests.","usability,testing,ux","Define success criteria and scenarios.","Run tests and capture behavior.","Analyze failures and recovery.","Report prioritized findings.","No critical task failure unaddressed.","Check task wording bias."),
("content-design","ui-ux-pro-max","Write clear UI copy, empty states, and errors.","content-design,copy,ux","Audit screens for unclear copy.","Rewrite for clarity and tone.","Check microcopy and errors.","Validate with content review.","No jargon or dead-end errors.","Check tone consistency."),
("design-tokens","ui-ux-pro-max","Manage color, spacing, and typography tokens.","design-tokens,tokens,ui","Audit token usage and naming.","Consolidate token sources.","Check theme and platform variants.","Validate with token linter/tests.","No orphaned hard-coded values.","Check token ownership."),
("frontend-architecture","software-development","Structure scalable frontend apps with clear boundaries.","frontend,architecture,web","Map features and data flow.","Draft module and state boundaries.","Check routing and code splitting.","Validate with build/lint/tests.","No circular dependency.","Check bundle size."),
("backend-architecture","software-development","Structure scalable backend services and APIs.","backend,architecture,api","Map domains and integrations.","Draft service and data ownership.","Check auth, queues, and caching.","Validate with integration tests.","No shared mutable state.","Check deployment boundaries."),
("fullstack-architecture","software-development","Integrate frontend, backend, data, and infra.","fullstack,architecture,integration","Map client/server/data boundaries.","Draft API, storage, and auth contracts.","Check CORS, caching, and errors.","Validate end-to-end.","No cross-layer coupling.","Check ownership and rollout."),
("clean-architecture","software-development","Organize code with entities, use cases, and adapters.","clean-architecture,ddd,design","Identify business rules.","Separate layers and dependencies.","Check dependency direction.","Validate with tests per layer.","No framework leakage inward.","Check boundary contracts."),
("domain-driven-design","software-development","Model bounded contexts, aggregates, and events.","ddd,domain,architecture","Identify domain boundaries.","Model aggregates and events.","Check context maps.","Validate with model tests.","No leaked aggregates.","Check ubiquituous language."),
("event-sourcing","software-development","Model state from immutable event logs.","event-sourcing,cqrs,events","Define event schema and store.","Draft projections and read models.","Check idempotency and snapshots.","Validate replay and projections.","No lost events.","Check event versioning."),
("cqrs-design","software-development","Separate command and query models safely.","cqrs,read-model,events","Define command and query boundaries.","Draft handlers and projections.","Check consistency and sync.","Validate read-model correctness.","No stale-read surprise.","Check consistency SLAs."),
("api-gateway-design","software-development","Route, secure, and observe API traffic centrally.","api-gateway,routing,platform","Define routes and policies.","Draft auth, rate limits, and observability.","Check timeouts and retries.","Validate routing and health.","No routing misconfiguration.","Check fallback behavior."),
("service-mesh-design","software-development","Manage east-west traffic, mTLS, and observability.","service-mesh,kubernetes,networking","Define mesh scope and policies.","Draft traffic and security rules.","Check latency and retries.","Validate with golden signals.","No traffic blackholing.","Check control plane health."),
("database-schema-migration","software-development","Manage schema changes with safe rollout and rollback.","database,migration,schema","Review schema change intent.","Draft migration and backfill.","Check locking and downtime.","Validate migrate/rollback.","No data loss or long lock.","Check compatibility window."),
("orm-optimization","software-development","Fix ORM N+1, hydration, and transaction issues.","orm,sql,performance","Capture slow queries and logs.","Inspect ORM mappings and sessions.","Check eager loading and transactions.","Run query plan and load tests.","No N+1 regression.","Check transaction boundaries."),
("search-ranking","software-development","Improve search relevance, recall, and latency.","search,ranking,retrieval","Audit queries and results.","Inspect index and scoring.","Check freshness and synonyms.","Validate with relevance tests.","No recall regression.","Check query semantics."),
("cache-architecture","software-development","Design cache layers, keys, and invalidation.","cache,architecture,performance","Identify hot reads and writes.","Draft cache tiers and TTLs.","Check invalidation and stampedes.","Validate hit/miss behavior.","No stale data surprise.","Check eviction policy."),
("web-security","security","Harden web apps with CSP, cookies, and input validation.","web,security,browser","Audit request sources and inputs.","Review headers, cookies, and CSP.","Check XSS/CSRF protections.","Validate with browser security tests.","No injection or session issue.","Check browser compatibility."),
("browser-automation","software-development","Automate browsers with stable selectors and waits.","browser,automation,testing","Capture failing step and selector.","Improve selectors and waits.","Check state assumptions and flake.","Run on clean environment.","No flaky automation.","Check runtime/version."),
("cli-design","software-development","Design ergonomic CLIs with help, errors, and piping.","cli,design,ux","Map commands and workflows.","Draft flags, help, and error codes.","Check piping and exit behavior.","Validate with shell scripts.","No silent failure or bad exit code.","Check shell compatibility."),
("plugin-architecture","software-development","Design plugin APIs, lifecycle, and sandboxing.","plugin,architecture,api","Define extension points.","Draft lifecycle and permissions.","Check isolation and versioning.","Validate with sample plugins.","No host crash from plugin.","Check compatibility contract."),
("workflow-automation","software-development","Automate repeatable workflows with idempotent steps.","automation,workflow,devops","List steps and failure modes.","Draft idempotent actions.","Check retries and notifications.","Run workflow on test fixture.","No partial state on failure.","Check cleanup and backoff."),
("data-visualization","data-engineering","Create clear charts, dashboards, and reports.","visualization,dashboard,analytics","Define metric and audience.","Choose chart type and scale.","Check accessibility and update cadence.","Validate with real dataset.","No misleading axis or aggregation.","Check refresh logic."),
("etl-testing","data-engineering","Test ETL jobs for completeness, nulls, and drift.","etl,testing,data","Define row and column contracts.","Draft data quality tests.","Check nulls, duplicates, and drift.","Run tests on sample data.","No silent data drift.","Check ownership."),
("stream-testing","data-engineering","Test stream jobs with replay and order assumptions.","streaming,testing,kafka","Define event contract and order.","Draft replay and validation tests.","Check late data and duplicates.","Run with recorded stream.","No state corruption.","Check consumer group behavior."),
("warehouse-modeling","data-engineering","Model warehouse marts, grains, and aggregates safely.","warehouse,modeling,sql","Define business questions and grains.","Draft marts and aggregates.","Check keys and filters.","Validate with query tests.","No metric drift.","Check lineage."),
("analytics-engineering","data-engineering","Build reliable metrics, definitions, and dashboards.","analytics,metrics,data","Define metric definitions and owners.","Draft dbt models and tests.","Check dimensions and filters.","Validate with metric diffs.","No metric drift.","Check documentation."),
("feature-store-design","machine-learning","Design feature store schemas, serving, and training consistency.","feature-store,ml,platform","Define feature contracts and freshness.","Draft offline/online paths.","Check point-in-time correctness.","Validate with training/serving parity.","No training-serving skew.","Check feature versioning."),
("experiment-design","machine-learning","Design AB experiments with power and unbiased metrics.","experiment,ab-test,statistics","Define hypothesis and metric.","Choose randomization and power.","Check guardrails and SUTVA.","Validate with pre/post analysis.","No peeking without correction.","Check sample ratio mismatch."),
("causal-inference","machine-learning","Estimate causal effects from observational data.","causality,inference,statistics","Define causal question and DAG.","Select identification strategy.","Check assumptions and sensitivity.","Validate with placebo or simulation.","No omitted-variable bias.","Check model assumptions."),
("time-series-analysis","machine-learning","Analyze trends, seasonality, and anomalies in time series.","time-series,analysis,statistics","Define frequency and horizon.","Inspect trend, season, and outliers.","Check stationarity and missingness.","Validate with train/test split.","No lookahead bias.","Check evaluation protocol."),
("bayesian-modeling","machine-learning","Build Bayesian models with priors and posterior checks.","bayesian,statistics,modeling","Define likelihood and priors.","Draft model and inference.","Check convergence and diagnostics.","Validate with posterior predictive checks.","No divergent transitions ignored.","Check prior sensitivity."),
("optimization","machine-learning","Formulate and solve optimization problems with constraints.","optimization,mathematical-modeling","Define objective and constraints.","Choose algorithm and solver.","Check scaling and feasibility.","Validate with benchmark instances.","No constraint violation accepted.","Check numerical stability."),
("graph-machine-learning","machine-learning","Train GNNs on graph data with batching and negative sampling.","graph,gnn,ml","Define graph schema and tasks.","Draft sampling and batching.","Check over-smoothing and splits.","Validate with link/node prediction.","No leakage across splits.","Check scalability."),
("ml-interpretability","machine-learning","Explain models with feature attribution and counterfactuals.","interpretability,explainability,ml","Choose explanation method and audience.","Draft attribution or counterexample.","Check faithfulness and stability.","Validate with sanity checks.","No false causal claims.","Check method assumptions."),
("recommendation-evaluation","machine-learning","Evaluate recommendation ranking and fairness.","recommendations,evaluation,ml","Define online/offline metrics.","Run offline ranking tests.","Check coverage and fairness.","Validate with online experiment.","No offline-only release.","Check bias and legality."),
("computer-vision-deployment","machine-learning","Deploy vision models with preprocessing and hardware checks.","computer-vision,deployment,inference","Define input contract and latency.","Package preprocessing and model.","Check device/driver support.","Validate with sample inputs.","No output format regression.","Check runtime compatibility."),
("audio-deployment","machine-learning","Deploy speech/audio models with format and latency checks.","audio,speech,deployment","Define audio format and SLA.","Package resampling and model.","Check noise robustness.","Validate with speech tests.","No format regression.","Check platform support."),
("robotics-integration","machine-learning","Integrate perception/planning models with robot interfaces.","robotics,integration,ml","Define sensor and actuator contracts.","Draft bridge and safety layer.","Check latency and safety limits.","Validate with simulator tests.","No unsafe action accepted.","Check emergency stop behavior."),
("autonomous-systems","machine-learning","Design safe autonomy with monitoring and fallback.","autonomous,robotics,safety","Define operational envelope.","Draft monitoring and fallbacks.","Check safety cases and redundancy.","Validate with scenario tests.","No unsafe fallback disabled.","Check human oversight."),
("blockchain-engineering","software-development","Design and debug blockchain apps and contracts.","blockchain,web3,smart-contracts","Map on-chain and off-chain trust.","Draft contracts and events.","Check gas, replay, and keys.","Validate with testnet fork.","No irreversible unsafe tx.","Check upgrade controls."),
("smart-contract-security","security","Audit smart contracts for reentrancy, access, and upgrades.","smart-contracts,security,blockchain","Inventory functions and owners.","Scan for known vulnerability classes.","Check upgrade and access controls.","Validate with fuzz/static analysis.","No unprotected critical function.","Check test coverage."),
("game-development","creative","Design and debug game loops, input, and state.","game,development,unity","Define core loop and states.","Draft input and scene structure.","Check performance and input lag.","Validate with playtest.","No input or state regression.","Check platform behavior."),
("unity-engineering","creative","Build Unity projects with components, scenes, and builds.","unity,csharp,gamedev","Define scene and component structure.","Draft systems and prefabs.","Check platform and input.","Validate with playmode and build.","No scene-load regression.","Check package compatibility."),
("unreal-engineering","creative","Build Unreal projects with blueprints/C++ and performance.","unreal,cpp,gamedev","Define gameplay framework.","Draft actors and subsystems.","Check cooking and profiling.","Validate with editor and standalone.","No cook regression.","Check engine version."),
("shader-development","creative","Write and debug GPU shaders for visuals and performance.","shaders,gpu,graphics","Define visual target and budget.","Draft shader and variants.","Check precision and performance.","Validate on target hardware.","No compile/runtime error.","Check shader model support."),
("technical-writing","research","Write clear docs, guides, and API references.","documentation,writing,technical","Define audience and scope.","Draft structure and examples.","Check accuracy and accessibility.","Validate with subject-matter review.","No stale example or API mismatch.","Check versioned docs."),
("open-source-maintenance","software-development","Run healthy open-source projects with triage and releases.","open-source,maintenance,community","Triage issues and PRs.","Set contributor and release rules.","Check changelog and compatibility.","Validate release artifacts.","No breaking change surprise.","Check license and security."),
]

from pathlib import Path
ROOT = Path("/root/VirgoYT-Hermes/skills")
for name, category, description, tags, step1, step2, step3, verify1, verify2, verify3 in rows:
    path = ROOT / category / name / "SKILL.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    title = name.replace("-", " ").title()
    trigger = description.lower().rstrip(".")
    body = TEMPLATE.format(
        name=name,
        description=description,
        tags=tags,
        title=title,
        trigger=trigger,
        step1=step1,
        step2=step2,
        step3=step3,
        verify1=verify1,
        verify2=verify2,
        verify3=verify3,
    )
    path.write_text(body, encoding="utf-8")
print("generated", len(rows), "skills")
